stages:
    data_ingestion:
      cmd: python src/components/data_ingestion.py
      deps:
        - src/components/data_ingestion.py
      outs:
        - Artifact/Data_ingestion/Ingested
        - Artifact/Data_ingestion/Raw_Data

    data_validation:
      cmd: python src/components/data_validation.py
      deps:
        - Artifact/Data_ingestion/Ingested
        - Artifact/Data_ingestion/Raw_Data
        - src/components/data_validation.py
      outs:
        - Artifact/Data_validation

    data_transformation:
      cmd: python src/components/data_transformation.py
      deps:
        - Artifact/Data_validation
        - src/components/data_transformation.py
      outs:
        - Artifact/Data_transformation/Transformed
        - Artifact/Data_transformation/Transformed_object

    model_training:
      cmd: python src/components/model_trainer.py
      deps:
        - Artifact/Data_transformation/Transformed
        - Artifact/Data_transformation/Transformed_object
        - src/components/model_trainer.py
      outs:
        - Artifact/Model_trainer/Trained_model

    model_evaluation:
      cmd: python src/components/model_evaluation.py
      deps:
        - Artifact/Model_trainer/Trained_model
        - src/components/model_evaluation.py
      outs:
        - Artifact/Model_evaluation

