stages:
    data_ingestion:
      cmd: python src/components/data_ingestion.py
      deps:
        - src/logger/__init__.py
        - src/exception/__init__.py
        - src/configuration/mongo_db_connection.py
        - src/constants/__init__.py
        - src/data_access/Fetch_Data.py
        - src/entity/config_entity.py
        - src/entity/artifact_entity.py
        - src/components/data_ingestion.py
      outs:
        - Artifact/Data_ingestion/Ingested
        - Artifact/Data_ingestion/Raw_Data