stages:
    data_ingestion:
      cmd: python src/components/data_ingestion.py
      deps:
        - src/logger/__init__.py
        - src/exception/__init__.py
        - src/configuration/mongo_db_connection.py
        - src/constants/__init__.py
        - src/data_access/Fetch_Data.py
        - src/entity/config_entity.py
        - src/entity/artifact_entity.py
        - src/components/data_ingestion.py
      outs:
        - Artifact/Data_ingestion/Ingested
        - Artifact/Data_ingestion/Raw_Data

    data_validation:
      cmd: python src/components/data_validation.py
      deps:
        - src/logger/__init__.py
        - src/exception/__init__.py
        - src/configuration/mongo_db_connection.py
        - src/constants/__init__.py
        - src/data_access/Fetch_Data.py
        - src/entity/config_entity.py
        - src/entity/artifact_entity.py
        - src/components/data_ingestion.py
        - config/schema.yaml 
        - src/components/data_validation.py
      outs:
        - Artifact/Data_validation

    data_transformation:
      cmd: python src/components/data_transformation.py
      deps:
        - src/logger/__init__.py
        - src/exception/__init__.py
        - src/configuration/mongo_db_connection.py
        - src/constants/__init__.py
        - src/data_access/Fetch_Data.py
        - src/entity/config_entity.py
        - src/entity/artifact_entity.py
        - src/components/data_ingestion.py
        - config/schema.yaml 
        - src/components/data_validation.py 
        - src/components/data_transformation.py
      outs:
        - Artifact/Data_transformation/Transformed
        - Artifact/Data_transformation/Transformed_object

    model_training:
      cmd: python src/components/model_trainer.py
      deps:
        - src/logger/__init__.py
        - src/exception/__init__.py
        - src/configuration/mongo_db_connection.py
        - src/constants/__init__.py
        - src/data_access/Fetch_Data.py
        - src/entity/config_entity.py
        - src/entity/artifact_entity.py
        - src/components/data_ingestion.py
        - config/schema.yaml 
        - src/components/data_validation.py 
        - src/components/data_transformation.py
        - src/entity/estimator.py
        - src/components/model_trainer.py
      outs:
        - Artifact/Model_trainer/Trained_model
