VotingClassifier:
  voting: "hard"
  estimators:
    - name: lr
      model: LogisticRegression
      params:
        C: 0.1
        l1_ratio: 0.05
        solver: saga

    - name: svm
      model: SVC

    - name: lgbm
      model: LGBMClassifier
      params:
        boosting_type: goss
        colsample_bytree: 1
        learning_rate: 0.01
        max_depth: 1
        min_child_samples: 50
        n_estimators: 100
        num_leaves: 10
        objective: binary
        reg_alpha: 0.01
        reg_lambda: 0.5
        subsample: 0.4

    - name: xgb
      model: XGBClassifier
      params:
        colsample_bytree: 1
        gamma: 0.1
        learning_rate: 0.3
        max_depth: 7
        n_estimators: 300
        alpha: 70
        min_child_weight: 4

    - name: ada
      model: AdaBoostClassifier
      params:
        algorithm: SAMME
        learning_rate: 0.1
        n_estimators: 100
        random_state: 42
        estimator:
          model: DecisionTreeClassifier
          params:
            max_depth: 9
            min_samples_leaf: 3
            min_samples_split: 5



 