name: CI Pipeline

on: push

jobs:
  Churn-Prediction:
    runs-on: ubuntu-latest

    # ✅ Make secret accessible as environment variable
    env:
      MDB_URL: ${{ secrets.MDB_URL }}

    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug secret loading (for testing only)
        run: |
          echo "Checking if MDB_URL is set"
          if [ -z "$MDB_URL" ]; then
            echo "MDB_URL is NOT set!"
            exit 1
          else
            echo "MDB_URL is set"
          fi

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run Pipeline
        run: dvc repro